{"uuid": "a6a63f0f-819b-4189-9d2b-3bd968858c95", "counter": 36, "stdout": "\u001b[0;31mAn exception occurred during task execution. To see the full traceback, use -vvv. The error was: AttributeError: 'str' object has no attribute 'is_absolute'\u001b[0m\r\n\u001b[0;31mfatal: [dnszone_dnszone_1]: FAILED! => {\"changed\": false, \"module_stderr\": \"Traceback (most recent call last):\\n  File \\\"/root/.ansible/tmp/ansible-tmp-1565573073.9792466-267616389491255/AnsiballZ_dnszone.py\\\", line 114, in <module>\\n    _ansiballz_main()\\n  File \\\"/root/.ansible/tmp/ansible-tmp-1565573073.9792466-267616389491255/AnsiballZ_dnszone.py\\\", line 106, in _ansiballz_main\\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\\n  File \\\"/root/.ansible/tmp/ansible-tmp-1565573073.9792466-267616389491255/AnsiballZ_dnszone.py\\\", line 49, in invoke_module\\n    imp.load_module('__main__', mod, module, MOD_DESC)\\n  File \\\"/tmp/ansible_dnszone_payload_VCP_bi/__main__.py\\\", line 191, in <module>\\n  File \\\"/tmp/ansible_dnszone_payload_VCP_bi/__main__.py\\\", line 188, in main\\n  File \\\"/tmp/ansible_dnszone_payload_VCP_bi/__main__.py\\\", line 154, in ensure\\n  File \\\"/tmp/ansible_dnszone_payload_VCP_bi/__main__.py\\\", line 121, in build_zone\\n  File \\\"/usr/lib/python2.7/site-packages/dns/zone.py\\\", line 242, in find_rdataset\\n    name = self._validate_name(name)\\n  File \\\"/usr/lib/python2.7/site-packages/dns/zone.py\\\", line 118, in _validate_name\\n    if not name.is_subdomain(self.origin):\\n  File \\\"/usr/lib/python2.7/site-packages/dns/name.py\\\", line 255, in is_subdomain\\n    (nr, o, nl) = self.fullcompare(other)\\n  File \\\"/usr/lib/python2.7/site-packages/dns/name.py\\\", line 205, in fullcompare\\n    oabs = other.is_absolute()\\nAttributeError: 'str' object has no attribute 'is_absolute'\\n\", \"module_stdout\": \"\", \"msg\": \"MODULE FAILURE\\nSee stdout/stderr for the exact error\", \"rc\": 1}\u001b[0m", "start_line": 34, "end_line": 36, "runner_ident": "dbff72b4-714f-40f9-a698-26dba2502065", "event": "runner_on_failed", "event_data": {"playbook": "integrations.yml", "playbook_uuid": "01449039-1a2d-4212-b837-6e52c875ecad", "play": "Run tests(s)", "play_uuid": "1c1b0dec-55e8-0d4b-a6d4-000000000009", "play_pattern": "containers", "task": "TEST1 | create zone", "task_uuid": "1c1b0dec-55e8-0d4b-a6d4-00000000003a", "task_action": "dnszone", "task_args": "", "task_path": "/home/phil/git/ansible-modules/tests/integrations/dnszone/tasks.yml:10", "host": "dnszone_dnszone_1", "remote_addr": "dnszone_dnszone_1", "res": {"module_stdout": "", "module_stderr": "Traceback (most recent call last):\n  File \"/root/.ansible/tmp/ansible-tmp-1565573073.9792466-267616389491255/AnsiballZ_dnszone.py\", line 114, in <module>\n    _ansiballz_main()\n  File \"/root/.ansible/tmp/ansible-tmp-1565573073.9792466-267616389491255/AnsiballZ_dnszone.py\", line 106, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/root/.ansible/tmp/ansible-tmp-1565573073.9792466-267616389491255/AnsiballZ_dnszone.py\", line 49, in invoke_module\n    imp.load_module('__main__', mod, module, MOD_DESC)\n  File \"/tmp/ansible_dnszone_payload_VCP_bi/__main__.py\", line 191, in <module>\n  File \"/tmp/ansible_dnszone_payload_VCP_bi/__main__.py\", line 188, in main\n  File \"/tmp/ansible_dnszone_payload_VCP_bi/__main__.py\", line 154, in ensure\n  File \"/tmp/ansible_dnszone_payload_VCP_bi/__main__.py\", line 121, in build_zone\n  File \"/usr/lib/python2.7/site-packages/dns/zone.py\", line 242, in find_rdataset\n    name = self._validate_name(name)\n  File \"/usr/lib/python2.7/site-packages/dns/zone.py\", line 118, in _validate_name\n    if not name.is_subdomain(self.origin):\n  File \"/usr/lib/python2.7/site-packages/dns/name.py\", line 255, in is_subdomain\n    (nr, o, nl) = self.fullcompare(other)\n  File \"/usr/lib/python2.7/site-packages/dns/name.py\", line 205, in fullcompare\n    oabs = other.is_absolute()\nAttributeError: 'str' object has no attribute 'is_absolute'\n", "exception": "Traceback (most recent call last):\n  File \"/root/.ansible/tmp/ansible-tmp-1565573073.9792466-267616389491255/AnsiballZ_dnszone.py\", line 114, in <module>\n    _ansiballz_main()\n  File \"/root/.ansible/tmp/ansible-tmp-1565573073.9792466-267616389491255/AnsiballZ_dnszone.py\", line 106, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/root/.ansible/tmp/ansible-tmp-1565573073.9792466-267616389491255/AnsiballZ_dnszone.py\", line 49, in invoke_module\n    imp.load_module('__main__', mod, module, MOD_DESC)\n  File \"/tmp/ansible_dnszone_payload_VCP_bi/__main__.py\", line 191, in <module>\n  File \"/tmp/ansible_dnszone_payload_VCP_bi/__main__.py\", line 188, in main\n  File \"/tmp/ansible_dnszone_payload_VCP_bi/__main__.py\", line 154, in ensure\n  File \"/tmp/ansible_dnszone_payload_VCP_bi/__main__.py\", line 121, in build_zone\n  File \"/usr/lib/python2.7/site-packages/dns/zone.py\", line 242, in find_rdataset\n    name = self._validate_name(name)\n  File \"/usr/lib/python2.7/site-packages/dns/zone.py\", line 118, in _validate_name\n    if not name.is_subdomain(self.origin):\n  File \"/usr/lib/python2.7/site-packages/dns/name.py\", line 255, in is_subdomain\n    (nr, o, nl) = self.fullcompare(other)\n  File \"/usr/lib/python2.7/site-packages/dns/name.py\", line 205, in fullcompare\n    oabs = other.is_absolute()\nAttributeError: 'str' object has no attribute 'is_absolute'\n", "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error", "rc": 1, "_ansible_no_log": false, "changed": false}, "ignore_errors": null, "event_loop": null, "pid": 7117}, "pid": 7117, "created": "2019-08-12T01:24:35.532164", "parent_uuid": "1c1b0dec-55e8-0d4b-a6d4-00000000003a"}