{"uuid": "319486df-05bd-43c9-84a2-db38e5475f0f", "counter": 36, "stdout": "\u001b[0;31mAn exception occurred during task execution. To see the full traceback, use -vvv. The error was: dns.exception.SyntaxError: expected EOL or EOF, got 3 \"192.168.50.2\"\u001b[0m\r\n\u001b[0;31mfatal: [dnszone_dnszone_1]: FAILED! => {\"changed\": false, \"module_stderr\": \"Traceback (most recent call last):\\n  File \\\"/root/.ansible/tmp/ansible-tmp-1565577522.7268627-119263123615261/AnsiballZ_dnszone.py\\\", line 114, in <module>\\n    _ansiballz_main()\\n  File \\\"/root/.ansible/tmp/ansible-tmp-1565577522.7268627-119263123615261/AnsiballZ_dnszone.py\\\", line 106, in _ansiballz_main\\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\\n  File \\\"/root/.ansible/tmp/ansible-tmp-1565577522.7268627-119263123615261/AnsiballZ_dnszone.py\\\", line 49, in invoke_module\\n    imp.load_module('__main__', mod, module, MOD_DESC)\\n  File \\\"/tmp/ansible_dnszone_payload_9jRXZX/__main__.py\\\", line 120, in <module>\\n  File \\\"/tmp/ansible_dnszone_payload_9jRXZX/__main__.py\\\", line 117, in main\\n  File \\\"/tmp/ansible_dnszone_payload_9jRXZX/__main__.py\\\", line 84, in ensure\\n  File \\\"/tmp/ansible_dnszone_payload_9jRXZX/__main__.py\\\", line 66, in build_zone\\n  File \\\"/usr/lib/python2.7/site-packages/dns/rdata.py\\\", line 433, in from_text\\n    return cls.from_text(rdclass, rdtype, tok, origin, relativize)\\n  File \\\"/usr/lib/python2.7/site-packages/dns/rdtypes/IN/A.py\\\", line 40, in from_text\\n    tok.get_eol()\\n  File \\\"/usr/lib/python2.7/site-packages/dns/tokenizer.py\\\", line 538, in get_eol\\n    raise dns.exception.SyntaxError('expected EOL or EOF, got %d \\\"%s\\\"' % (token.ttype, token.value))\\ndns.exception.SyntaxError: expected EOL or EOF, got 3 \\\"192.168.50.2\\\"\\n\", \"module_stdout\": \"\", \"msg\": \"MODULE FAILURE\\nSee stdout/stderr for the exact error\", \"rc\": 1}\u001b[0m", "start_line": 34, "end_line": 36, "runner_ident": "5b4c8251-9b03-41f1-a959-76b1617b1a79", "event": "runner_on_failed", "event_data": {"playbook": "integrations.yml", "playbook_uuid": "22635238-f295-43df-ba26-22fc4fe730c1", "play": "Run tests(s)", "play_uuid": "1c1b0dec-55e8-e48e-de57-000000000009", "play_pattern": "containers", "task": "TEST1 | create zone", "task_uuid": "1c1b0dec-55e8-e48e-de57-00000000003a", "task_action": "dnszone", "task_args": "", "task_path": "/home/phil/git/ansible-modules/tests/integrations/dnszone/tasks.yml:10", "host": "dnszone_dnszone_1", "remote_addr": "dnszone_dnszone_1", "res": {"module_stdout": "", "module_stderr": "Traceback (most recent call last):\n  File \"/root/.ansible/tmp/ansible-tmp-1565577522.7268627-119263123615261/AnsiballZ_dnszone.py\", line 114, in <module>\n    _ansiballz_main()\n  File \"/root/.ansible/tmp/ansible-tmp-1565577522.7268627-119263123615261/AnsiballZ_dnszone.py\", line 106, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/root/.ansible/tmp/ansible-tmp-1565577522.7268627-119263123615261/AnsiballZ_dnszone.py\", line 49, in invoke_module\n    imp.load_module('__main__', mod, module, MOD_DESC)\n  File \"/tmp/ansible_dnszone_payload_9jRXZX/__main__.py\", line 120, in <module>\n  File \"/tmp/ansible_dnszone_payload_9jRXZX/__main__.py\", line 117, in main\n  File \"/tmp/ansible_dnszone_payload_9jRXZX/__main__.py\", line 84, in ensure\n  File \"/tmp/ansible_dnszone_payload_9jRXZX/__main__.py\", line 66, in build_zone\n  File \"/usr/lib/python2.7/site-packages/dns/rdata.py\", line 433, in from_text\n    return cls.from_text(rdclass, rdtype, tok, origin, relativize)\n  File \"/usr/lib/python2.7/site-packages/dns/rdtypes/IN/A.py\", line 40, in from_text\n    tok.get_eol()\n  File \"/usr/lib/python2.7/site-packages/dns/tokenizer.py\", line 538, in get_eol\n    raise dns.exception.SyntaxError('expected EOL or EOF, got %d \"%s\"' % (token.ttype, token.value))\ndns.exception.SyntaxError: expected EOL or EOF, got 3 \"192.168.50.2\"\n", "exception": "Traceback (most recent call last):\n  File \"/root/.ansible/tmp/ansible-tmp-1565577522.7268627-119263123615261/AnsiballZ_dnszone.py\", line 114, in <module>\n    _ansiballz_main()\n  File \"/root/.ansible/tmp/ansible-tmp-1565577522.7268627-119263123615261/AnsiballZ_dnszone.py\", line 106, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/root/.ansible/tmp/ansible-tmp-1565577522.7268627-119263123615261/AnsiballZ_dnszone.py\", line 49, in invoke_module\n    imp.load_module('__main__', mod, module, MOD_DESC)\n  File \"/tmp/ansible_dnszone_payload_9jRXZX/__main__.py\", line 120, in <module>\n  File \"/tmp/ansible_dnszone_payload_9jRXZX/__main__.py\", line 117, in main\n  File \"/tmp/ansible_dnszone_payload_9jRXZX/__main__.py\", line 84, in ensure\n  File \"/tmp/ansible_dnszone_payload_9jRXZX/__main__.py\", line 66, in build_zone\n  File \"/usr/lib/python2.7/site-packages/dns/rdata.py\", line 433, in from_text\n    return cls.from_text(rdclass, rdtype, tok, origin, relativize)\n  File \"/usr/lib/python2.7/site-packages/dns/rdtypes/IN/A.py\", line 40, in from_text\n    tok.get_eol()\n  File \"/usr/lib/python2.7/site-packages/dns/tokenizer.py\", line 538, in get_eol\n    raise dns.exception.SyntaxError('expected EOL or EOF, got %d \"%s\"' % (token.ttype, token.value))\ndns.exception.SyntaxError: expected EOL or EOF, got 3 \"192.168.50.2\"\n", "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error", "rc": 1, "_ansible_no_log": false, "changed": false}, "ignore_errors": null, "event_loop": null, "pid": 5817}, "pid": 5817, "created": "2019-08-12T02:38:44.140542", "parent_uuid": "1c1b0dec-55e8-e48e-de57-00000000003a"}