{"uuid": "3223c363-5c84-4fa3-8524-1078ac6d8af5", "counter": 36, "stdout": "\u001b[0;31mAn exception occurred during task execution. To see the full traceback, use -vvv. The error was: AttributeError: 'str' object has no attribute 'is_absolute'\u001b[0m\r\n\u001b[0;31mfatal: [dnszone_dnszone_1]: FAILED! => {\"changed\": false, \"module_stderr\": \"Traceback (most recent call last):\\n  File \\\"/root/.ansible/tmp/ansible-tmp-1565576183.6307113-123117656317859/AnsiballZ_dnszone.py\\\", line 114, in <module>\\n    _ansiballz_main()\\n  File \\\"/root/.ansible/tmp/ansible-tmp-1565576183.6307113-123117656317859/AnsiballZ_dnszone.py\\\", line 106, in _ansiballz_main\\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\\n  File \\\"/root/.ansible/tmp/ansible-tmp-1565576183.6307113-123117656317859/AnsiballZ_dnszone.py\\\", line 49, in invoke_module\\n    imp.load_module('__main__', mod, module, MOD_DESC)\\n  File \\\"/tmp/ansible_dnszone_payload_lGjcRy/__main__.py\\\", line 118, in <module>\\n  File \\\"/tmp/ansible_dnszone_payload_lGjcRy/__main__.py\\\", line 115, in main\\n  File \\\"/tmp/ansible_dnszone_payload_lGjcRy/__main__.py\\\", line 81, in ensure\\n  File \\\"/tmp/ansible_dnszone_payload_lGjcRy/__main__.py\\\", line 59, in build_zone\\n  File \\\"/usr/lib/python2.7/site-packages/dns/zone.py\\\", line 242, in find_rdataset\\n    name = self._validate_name(name)\\n  File \\\"/usr/lib/python2.7/site-packages/dns/zone.py\\\", line 118, in _validate_name\\n    if not name.is_subdomain(self.origin):\\n  File \\\"/usr/lib/python2.7/site-packages/dns/name.py\\\", line 255, in is_subdomain\\n    (nr, o, nl) = self.fullcompare(other)\\n  File \\\"/usr/lib/python2.7/site-packages/dns/name.py\\\", line 205, in fullcompare\\n    oabs = other.is_absolute()\\nAttributeError: 'str' object has no attribute 'is_absolute'\\n\", \"module_stdout\": \"\", \"msg\": \"MODULE FAILURE\\nSee stdout/stderr for the exact error\", \"rc\": 1}\u001b[0m", "start_line": 34, "end_line": 36, "runner_ident": "c9b6f176-1bfc-4240-a73e-d0777254abce", "event": "runner_on_failed", "event_data": {"playbook": "integrations.yml", "playbook_uuid": "dfcd218b-3705-417a-bf17-6361cc279e3c", "play": "Run tests(s)", "play_uuid": "1c1b0dec-55e8-58b9-aed8-000000000009", "play_pattern": "containers", "task": "TEST1 | create zone", "task_uuid": "1c1b0dec-55e8-58b9-aed8-00000000003a", "task_action": "dnszone", "task_args": "", "task_path": "/home/phil/git/ansible-modules/tests/integrations/dnszone/tasks.yml:10", "host": "dnszone_dnszone_1", "remote_addr": "dnszone_dnszone_1", "res": {"module_stdout": "", "module_stderr": "Traceback (most recent call last):\n  File \"/root/.ansible/tmp/ansible-tmp-1565576183.6307113-123117656317859/AnsiballZ_dnszone.py\", line 114, in <module>\n    _ansiballz_main()\n  File \"/root/.ansible/tmp/ansible-tmp-1565576183.6307113-123117656317859/AnsiballZ_dnszone.py\", line 106, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/root/.ansible/tmp/ansible-tmp-1565576183.6307113-123117656317859/AnsiballZ_dnszone.py\", line 49, in invoke_module\n    imp.load_module('__main__', mod, module, MOD_DESC)\n  File \"/tmp/ansible_dnszone_payload_lGjcRy/__main__.py\", line 118, in <module>\n  File \"/tmp/ansible_dnszone_payload_lGjcRy/__main__.py\", line 115, in main\n  File \"/tmp/ansible_dnszone_payload_lGjcRy/__main__.py\", line 81, in ensure\n  File \"/tmp/ansible_dnszone_payload_lGjcRy/__main__.py\", line 59, in build_zone\n  File \"/usr/lib/python2.7/site-packages/dns/zone.py\", line 242, in find_rdataset\n    name = self._validate_name(name)\n  File \"/usr/lib/python2.7/site-packages/dns/zone.py\", line 118, in _validate_name\n    if not name.is_subdomain(self.origin):\n  File \"/usr/lib/python2.7/site-packages/dns/name.py\", line 255, in is_subdomain\n    (nr, o, nl) = self.fullcompare(other)\n  File \"/usr/lib/python2.7/site-packages/dns/name.py\", line 205, in fullcompare\n    oabs = other.is_absolute()\nAttributeError: 'str' object has no attribute 'is_absolute'\n", "exception": "Traceback (most recent call last):\n  File \"/root/.ansible/tmp/ansible-tmp-1565576183.6307113-123117656317859/AnsiballZ_dnszone.py\", line 114, in <module>\n    _ansiballz_main()\n  File \"/root/.ansible/tmp/ansible-tmp-1565576183.6307113-123117656317859/AnsiballZ_dnszone.py\", line 106, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/root/.ansible/tmp/ansible-tmp-1565576183.6307113-123117656317859/AnsiballZ_dnszone.py\", line 49, in invoke_module\n    imp.load_module('__main__', mod, module, MOD_DESC)\n  File \"/tmp/ansible_dnszone_payload_lGjcRy/__main__.py\", line 118, in <module>\n  File \"/tmp/ansible_dnszone_payload_lGjcRy/__main__.py\", line 115, in main\n  File \"/tmp/ansible_dnszone_payload_lGjcRy/__main__.py\", line 81, in ensure\n  File \"/tmp/ansible_dnszone_payload_lGjcRy/__main__.py\", line 59, in build_zone\n  File \"/usr/lib/python2.7/site-packages/dns/zone.py\", line 242, in find_rdataset\n    name = self._validate_name(name)\n  File \"/usr/lib/python2.7/site-packages/dns/zone.py\", line 118, in _validate_name\n    if not name.is_subdomain(self.origin):\n  File \"/usr/lib/python2.7/site-packages/dns/name.py\", line 255, in is_subdomain\n    (nr, o, nl) = self.fullcompare(other)\n  File \"/usr/lib/python2.7/site-packages/dns/name.py\", line 205, in fullcompare\n    oabs = other.is_absolute()\nAttributeError: 'str' object has no attribute 'is_absolute'\n", "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error", "rc": 1, "_ansible_no_log": false, "changed": false}, "ignore_errors": null, "event_loop": null, "pid": 22152}, "pid": 22152, "created": "2019-08-12T02:16:25.047010", "parent_uuid": "1c1b0dec-55e8-58b9-aed8-00000000003a"}