{"uuid": "e554ecaa-df73-443b-a92f-41c0c59e67d0", "counter": 36, "stdout": "\u001b[0;31mAn exception occurred during task execution. To see the full traceback, use -vvv. The error was: AttributeError: 'str' object has no attribute 'is_absolute'\u001b[0m\r\n\u001b[0;31mfatal: [dnszone_dnszone_1]: FAILED! => {\"changed\": false, \"module_stderr\": \"Traceback (most recent call last):\\n  File \\\"/root/.ansible/tmp/ansible-tmp-1565576947.7686996-113681354363658/AnsiballZ_dnszone.py\\\", line 114, in <module>\\n    _ansiballz_main()\\n  File \\\"/root/.ansible/tmp/ansible-tmp-1565576947.7686996-113681354363658/AnsiballZ_dnszone.py\\\", line 106, in _ansiballz_main\\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\\n  File \\\"/root/.ansible/tmp/ansible-tmp-1565576947.7686996-113681354363658/AnsiballZ_dnszone.py\\\", line 49, in invoke_module\\n    imp.load_module('__main__', mod, module, MOD_DESC)\\n  File \\\"/tmp/ansible_dnszone_payload_7GRYBt/__main__.py\\\", line 121, in <module>\\n  File \\\"/tmp/ansible_dnszone_payload_7GRYBt/__main__.py\\\", line 118, in main\\n  File \\\"/tmp/ansible_dnszone_payload_7GRYBt/__main__.py\\\", line 91, in ensure\\n  File \\\"/usr/lib/python2.7/site-packages/dns/zone.py\\\", line 499, in to_file\\n    relativize=relativize)\\n  File \\\"/usr/lib/python2.7/site-packages/dns/node.py\\\", line 53, in to_text\\n    print >> s, rds.to_text(name, **kw)\\n  File \\\"/usr/lib/python2.7/site-packages/dns/rdataset.py\\\", line 187, in to_text\\n    name = name.choose_relativity(origin, relativize)\\n  File \\\"/usr/lib/python2.7/site-packages/dns/name.py\\\", line 525, in choose_relativity\\n    return self.relativize(origin)\\n  File \\\"/usr/lib/python2.7/site-packages/dns/name.py\\\", line 499, in relativize\\n    if not origin is None and self.is_subdomain(origin):\\n  File \\\"/usr/lib/python2.7/site-packages/dns/name.py\\\", line 255, in is_subdomain\\n    (nr, o, nl) = self.fullcompare(other)\\n  File \\\"/usr/lib/python2.7/site-packages/dns/name.py\\\", line 205, in fullcompare\\n    oabs = other.is_absolute()\\nAttributeError: 'str' object has no attribute 'is_absolute'\\n\", \"module_stdout\": \"\", \"msg\": \"MODULE FAILURE\\nSee stdout/stderr for the exact error\", \"rc\": 1}\u001b[0m", "start_line": 34, "end_line": 36, "runner_ident": "50097003-c523-48f1-a595-0315e6a660bb", "event": "runner_on_failed", "event_data": {"playbook": "integrations.yml", "playbook_uuid": "3e5a8e9e-1a6d-4406-a65f-241aa1d7872c", "play": "Run tests(s)", "play_uuid": "1c1b0dec-55e8-1d1d-8d4a-000000000009", "play_pattern": "containers", "task": "TEST1 | create zone", "task_uuid": "1c1b0dec-55e8-1d1d-8d4a-00000000003a", "task_action": "dnszone", "task_args": "", "task_path": "/home/phil/git/ansible-modules/tests/integrations/dnszone/tasks.yml:10", "host": "dnszone_dnszone_1", "remote_addr": "dnszone_dnszone_1", "res": {"module_stdout": "", "module_stderr": "Traceback (most recent call last):\n  File \"/root/.ansible/tmp/ansible-tmp-1565576947.7686996-113681354363658/AnsiballZ_dnszone.py\", line 114, in <module>\n    _ansiballz_main()\n  File \"/root/.ansible/tmp/ansible-tmp-1565576947.7686996-113681354363658/AnsiballZ_dnszone.py\", line 106, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/root/.ansible/tmp/ansible-tmp-1565576947.7686996-113681354363658/AnsiballZ_dnszone.py\", line 49, in invoke_module\n    imp.load_module('__main__', mod, module, MOD_DESC)\n  File \"/tmp/ansible_dnszone_payload_7GRYBt/__main__.py\", line 121, in <module>\n  File \"/tmp/ansible_dnszone_payload_7GRYBt/__main__.py\", line 118, in main\n  File \"/tmp/ansible_dnszone_payload_7GRYBt/__main__.py\", line 91, in ensure\n  File \"/usr/lib/python2.7/site-packages/dns/zone.py\", line 499, in to_file\n    relativize=relativize)\n  File \"/usr/lib/python2.7/site-packages/dns/node.py\", line 53, in to_text\n    print >> s, rds.to_text(name, **kw)\n  File \"/usr/lib/python2.7/site-packages/dns/rdataset.py\", line 187, in to_text\n    name = name.choose_relativity(origin, relativize)\n  File \"/usr/lib/python2.7/site-packages/dns/name.py\", line 525, in choose_relativity\n    return self.relativize(origin)\n  File \"/usr/lib/python2.7/site-packages/dns/name.py\", line 499, in relativize\n    if not origin is None and self.is_subdomain(origin):\n  File \"/usr/lib/python2.7/site-packages/dns/name.py\", line 255, in is_subdomain\n    (nr, o, nl) = self.fullcompare(other)\n  File \"/usr/lib/python2.7/site-packages/dns/name.py\", line 205, in fullcompare\n    oabs = other.is_absolute()\nAttributeError: 'str' object has no attribute 'is_absolute'\n", "exception": "Traceback (most recent call last):\n  File \"/root/.ansible/tmp/ansible-tmp-1565576947.7686996-113681354363658/AnsiballZ_dnszone.py\", line 114, in <module>\n    _ansiballz_main()\n  File \"/root/.ansible/tmp/ansible-tmp-1565576947.7686996-113681354363658/AnsiballZ_dnszone.py\", line 106, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/root/.ansible/tmp/ansible-tmp-1565576947.7686996-113681354363658/AnsiballZ_dnszone.py\", line 49, in invoke_module\n    imp.load_module('__main__', mod, module, MOD_DESC)\n  File \"/tmp/ansible_dnszone_payload_7GRYBt/__main__.py\", line 121, in <module>\n  File \"/tmp/ansible_dnszone_payload_7GRYBt/__main__.py\", line 118, in main\n  File \"/tmp/ansible_dnszone_payload_7GRYBt/__main__.py\", line 91, in ensure\n  File \"/usr/lib/python2.7/site-packages/dns/zone.py\", line 499, in to_file\n    relativize=relativize)\n  File \"/usr/lib/python2.7/site-packages/dns/node.py\", line 53, in to_text\n    print >> s, rds.to_text(name, **kw)\n  File \"/usr/lib/python2.7/site-packages/dns/rdataset.py\", line 187, in to_text\n    name = name.choose_relativity(origin, relativize)\n  File \"/usr/lib/python2.7/site-packages/dns/name.py\", line 525, in choose_relativity\n    return self.relativize(origin)\n  File \"/usr/lib/python2.7/site-packages/dns/name.py\", line 499, in relativize\n    if not origin is None and self.is_subdomain(origin):\n  File \"/usr/lib/python2.7/site-packages/dns/name.py\", line 255, in is_subdomain\n    (nr, o, nl) = self.fullcompare(other)\n  File \"/usr/lib/python2.7/site-packages/dns/name.py\", line 205, in fullcompare\n    oabs = other.is_absolute()\nAttributeError: 'str' object has no attribute 'is_absolute'\n", "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error", "rc": 1, "_ansible_no_log": false, "changed": false}, "ignore_errors": null, "event_loop": null, "pid": 31745}, "pid": 31745, "created": "2019-08-12T02:29:09.205777", "parent_uuid": "1c1b0dec-55e8-1d1d-8d4a-00000000003a"}