[1;35m [WARNING]: Unable to parse /home/phil/git/ansible-modules/tests/inventory as[0m
[1;35man inventory source[0m
[1;35m[0m
[1;35m [WARNING]: No inventory was parsed, only implicit localhost is available[0m
[1;35m[0m
[1;35m [WARNING]: provided hosts list is empty, only localhost is available. Note[0m
[1;35mthat the implicit localhost does not match 'all'[0m
[1;35m[0m
[1;35m [WARNING]: Could not match supplied host pattern, ignoring: containers[0m
[1;35m[0m

PLAY [Setup test env] **********************************************************

TASK [Gathering Facts] *********************************************************
[0;32mok: [localhost][0m

TASK [deploy test env] *********************************************************
[0;32mok: [localhost -> localhost][0m

TASK [add host] ****************************************************************
[0;33mchanged: [localhost] => (item=dnszone_dnszone_1)[0m

PLAY [Run tests(s)] ************************************************************

TASK [Gathering Facts] *********************************************************
[0;32mok: [dnszone_dnszone_1][0m

TASK [include] *****************************************************************
[0;36mincluded: /home/phil/git/ansible-modules/tests/integrations/dnszone/tasks.yml for dnszone_dnszone_1[0m

TASK [TEST | prep environment] *************************************************
[0;32mok: [dnszone_dnszone_1][0m

TASK [TEST1 | create zone] *****************************************************
[0;31mAn exception occurred during task execution. To see the full traceback, use -vvv. The error was: TypeError: from_text() takes at most 5 arguments (9 given)[0m
[0;31mfatal: [dnszone_dnszone_1]: FAILED! => {"changed": false, "module_stderr": "Traceback (most recent call last):\n  File \"/root/.ansible/tmp/ansible-tmp-1565576351.9907367-196274380833914/AnsiballZ_dnszone.py\", line 114, in <module>\n    _ansiballz_main()\n  File \"/root/.ansible/tmp/ansible-tmp-1565576351.9907367-196274380833914/AnsiballZ_dnszone.py\", line 106, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/root/.ansible/tmp/ansible-tmp-1565576351.9907367-196274380833914/AnsiballZ_dnszone.py\", line 49, in invoke_module\n    imp.load_module('__main__', mod, module, MOD_DESC)\n  File \"/tmp/ansible_dnszone_payload_3thD7u/__main__.py\", line 118, in <module>\n  File \"/tmp/ansible_dnszone_payload_3thD7u/__main__.py\", line 115, in main\n  File \"/tmp/ansible_dnszone_payload_3thD7u/__main__.py\", line 81, in ensure\n  File \"/tmp/ansible_dnszone_payload_3thD7u/__main__.py\", line 61, in build_zone\nTypeError: from_text() takes at most 5 arguments (9 given)\n", "module_stdout": "", "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error", "rc": 1}[0m
[0;31mdnszone_dnszone_1[0m          : [0;32mok=3   [0m changed=0    unreachable=0    [0;31mfailed=1   [0m skipped=0    rescued=0    ignored=0   
[0;33mlocalhost[0m                  : [0;32mok=3   [0m [0;33mchanged=1   [0m unreachable=0    failed=0    skipped=0    rescued=0    ignored=0   


PLAY RECAP *********************************************************************
[0;31mdnszone_dnszone_1[0m          : [0;32mok=3   [0m changed=0    unreachable=0    [0;31mfailed=1   [0m skipped=0    rescued=0    ignored=0   
[0;33mlocalhost[0m                  : [0;32mok=3   [0m [0;33mchanged=1   [0m unreachable=0    failed=0    skipped=0    rescued=0    ignored=0   

