[1;35m [WARNING]: Unable to parse /home/phil/git/ansible-modules/tests/inventory as[0m
[1;35man inventory source[0m
[1;35m[0m
[1;35m [WARNING]: No inventory was parsed, only implicit localhost is available[0m
[1;35m[0m
[1;35m [WARNING]: provided hosts list is empty, only localhost is available. Note[0m
[1;35mthat the implicit localhost does not match 'all'[0m
[1;35m[0m
[1;35m [WARNING]: Could not match supplied host pattern, ignoring: containers[0m
[1;35m[0m

PLAY [Setup test env] **********************************************************

TASK [Gathering Facts] *********************************************************
[0;32mok: [localhost][0m

TASK [deploy test env] *********************************************************
[0;33mchanged: [localhost -> localhost][0m

TASK [add host] ****************************************************************
[0;33mchanged: [localhost] => (item=dnszone_dnszone_1)[0m

PLAY [Run tests(s)] ************************************************************

TASK [Gathering Facts] *********************************************************
[0;32mok: [dnszone_dnszone_1][0m

TASK [include] *****************************************************************
[0;36mincluded: /home/phil/git/ansible-modules/tests/integrations/dnszone/tasks.yml for dnszone_dnszone_1[0m

TASK [TEST | prep environment] *************************************************
[0;33mchanged: [dnszone_dnszone_1][0m

TASK [TEST1 | create zone] *****************************************************
[0;31mAn exception occurred during task execution. To see the full traceback, use -vvv. The error was: AttributeError: 'str' object has no attribute 'is_absolute'[0m
[0;31mfatal: [dnszone_dnszone_1]: FAILED! => {"changed": false, "module_stderr": "Traceback (most recent call last):\n  File \"/root/.ansible/tmp/ansible-tmp-1565573073.9792466-267616389491255/AnsiballZ_dnszone.py\", line 114, in <module>\n    _ansiballz_main()\n  File \"/root/.ansible/tmp/ansible-tmp-1565573073.9792466-267616389491255/AnsiballZ_dnszone.py\", line 106, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/root/.ansible/tmp/ansible-tmp-1565573073.9792466-267616389491255/AnsiballZ_dnszone.py\", line 49, in invoke_module\n    imp.load_module('__main__', mod, module, MOD_DESC)\n  File \"/tmp/ansible_dnszone_payload_VCP_bi/__main__.py\", line 191, in <module>\n  File \"/tmp/ansible_dnszone_payload_VCP_bi/__main__.py\", line 188, in main\n  File \"/tmp/ansible_dnszone_payload_VCP_bi/__main__.py\", line 154, in ensure\n  File \"/tmp/ansible_dnszone_payload_VCP_bi/__main__.py\", line 121, in build_zone\n  File \"/usr/lib/python2.7/site-packages/dns/zone.py\", line 242, in find_rdataset\n    name = self._validate_name(name)\n  File \"/usr/lib/python2.7/site-packages/dns/zone.py\", line 118, in _validate_name\n    if not name.is_subdomain(self.origin):\n  File \"/usr/lib/python2.7/site-packages/dns/name.py\", line 255, in is_subdomain\n    (nr, o, nl) = self.fullcompare(other)\n  File \"/usr/lib/python2.7/site-packages/dns/name.py\", line 205, in fullcompare\n    oabs = other.is_absolute()\nAttributeError: 'str' object has no attribute 'is_absolute'\n", "module_stdout": "", "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error", "rc": 1}[0m

PLAY RECAP *********************************************************************
[0;31mdnszone_dnszone_1[0m          : [0;32mok=3   [0m [0;33mchanged=1   [0m unreachable=0    [0;31mfailed=1   [0m skipped=0    rescued=0    ignored=0   
[0;33mlocalhost[0m                  : [0;32mok=3   [0m [0;33mchanged=2   [0m unreachable=0    failed=0    skipped=0    rescued=0    ignored=0   

